const dummyGroups = [
  [
    "138204",
    {
      group: {
        isProxy: true,
        options: {},
        name: "Gruppe 1",
        createdAt: 1503241136,
        instanceId: 138204,
        onOff: false,
        dimmer: 0,
        deviceIDs: [65537],
        sceneId: 203167,
        groupType: 0,
      },
      scenes: {
        "203167": {
          isProxy: true,
          options: {},
          name: "RELAX",
          createdAt: 1503241136,
          instanceId: 203167,
          isActive: false,
          isPredefined: true,
          lightSettings: [
            {
              isProxy: true,
              options: {},
              name: "",
              createdAt: 0,
              instanceId: 65537,
              color: "f1e0b5",
              hue: 0,
              saturation: 0,
              colorX: 0,
              colorY: 0,
              colorTemperature: 0,
              dimmer: 9.8,
              onOff: true,
            },
          ],
          sceneIndex: 1,
          useCurrentLightSettings: false,
        },
        "217570": {
          isProxy: true,
          options: {},
          name: "EVERYDAY",
          createdAt: 1503241136,
          instanceId: 217570,
          isActive: false,
          isPredefined: true,
          lightSettings: [
            {
              isProxy: true,
              options: {},
              name: "",
              createdAt: 0,
              instanceId: 65537,
              color: "f1e0b5",
              hue: 0,
              saturation: 0,
              colorX: 0,
              colorY: 0,
              colorTemperature: 0,
              dimmer: 79.9,
              onOff: true,
            },
          ],
          sceneIndex: 0,
          useCurrentLightSettings: false,
        },
        "225993": {
          isProxy: true,
          options: {},
          name: "FOCUS",
          createdAt: 1503241136,
          instanceId: 225993,
          isActive: false,
          isPredefined: true,
          lightSettings: [
            {
              isProxy: true,
              options: {},
              name: "",
              createdAt: 0,
              instanceId: 65537,
              color: "f1e0b5",
              hue: 0,
              saturation: 0,
              colorX: 0,
              colorY: 0,
              colorTemperature: 0,
              dimmer: 100,
              onOff: true,
            },
          ],
          sceneIndex: 2,
          useCurrentLightSettings: false,
        },
      },
    },
  ],
  [
    "154125",
    {
      group: {
        isProxy: true,
        options: {},
        name: "Group 2",
        createdAt: 1504795182,
        instanceId: 154125,
        onOff: false,
        dimmer: 0,
        deviceIDs: [65542],
        sceneId: 215618,
        groupType: 0,
      },
      scenes: {
        "199636": {
          isProxy: true,
          options: {},
          name: "RELAX",
          createdAt: 1504795182,
          instanceId: 199636,
          isActive: false,
          isPredefined: true,
          lightSettings: [],
          sceneIndex: 1,
          useCurrentLightSettings: false,
        },
        "215618": {
          isProxy: true,
          options: {},
          name: "EVERYDAY",
          createdAt: 1504795182,
          instanceId: 215618,
          isActive: false,
          isPredefined: true,
          lightSettings: [],
          sceneIndex: 0,
          useCurrentLightSettings: false,
        },
        "223800": {
          isProxy: true,
          options: {},
          name: "FOCUS",
          createdAt: 1504795182,
          instanceId: 223800,
          isActive: false,
          isPredefined: true,
          lightSettings: [],
          sceneIndex: 2,
          useCurrentLightSettings: false,
        },
      },
    },
  ],
  [
    "158564",
    {
      group: {
        isProxy: true,
        options: {},
        name: "Group 3",
        createdAt: 1504795450,
        instanceId: 158564,
        onOff: false,
        dimmer: 0,
        deviceIDs: [65543, 65539, 65541, 65540],
        sceneId: 225994,
        groupType: 0,
      },
      scenes: {
        "203571": {
          isProxy: true,
          options: {},
          name: "RELAX",
          createdAt: 1504795450,
          instanceId: 203571,
          isActive: false,
          isPredefined: true,
          lightSettings: [
            {
              isProxy: true,
              options: {},
              name: "",
              createdAt: 0,
              instanceId: 65539,
              color: "f1e0b5",
              hue: 0,
              saturation: 0,
              colorX: 0,
              colorY: 0,
              colorTemperature: 0,
              dimmer: 9.8,
              onOff: true,
            },
            {
              isProxy: true,
              options: {},
              name: "",
              createdAt: 0,
              instanceId: 65541,
              color: "f1e0b5",
              hue: 0,
              saturation: 0,
              colorX: 0,
              colorY: 0,
              colorTemperature: 0,
              dimmer: 9.8,
              onOff: true,
            },
            {
              isProxy: true,
              options: {},
              name: "",
              createdAt: 0,
              instanceId: 65540,
              color: "f1e0b5",
              hue: 0,
              saturation: 0,
              colorX: 0,
              colorY: 0,
              colorTemperature: 0,
              dimmer: 9.8,
              onOff: true,
            },
          ],
          sceneIndex: 1,
          useCurrentLightSettings: false,
        },
        "205876": {
          isProxy: true,
          options: {},
          name: "EVERYDAY",
          createdAt: 1504795450,
          instanceId: 205876,
          isActive: false,
          isPredefined: true,
          lightSettings: [
            {
              isProxy: true,
              options: {},
              name: "",
              createdAt: 0,
              instanceId: 65539,
              color: "f1e0b5",
              hue: 0,
              saturation: 0,
              colorX: 0,
              colorY: 0,
              colorTemperature: 0,
              dimmer: 79.9,
              onOff: true,
            },
            {
              isProxy: true,
              options: {},
              name: "",
              createdAt: 0,
              instanceId: 65541,
              color: "f1e0b5",
              hue: 0,
              saturation: 0,
              colorX: 0,
              colorY: 0,
              colorTemperature: 0,
              dimmer: 79.9,
              onOff: true,
            },
            {
              isProxy: true,
              options: {},
              name: "",
              createdAt: 0,
              instanceId: 65540,
              color: "f1e0b5",
              hue: 0,
              saturation: 0,
              colorX: 0,
              colorY: 0,
              colorTemperature: 0,
              dimmer: 79.9,
              onOff: true,
            },
          ],
          sceneIndex: 0,
          useCurrentLightSettings: false,
        },
        "221759": {
          isProxy: true,
          options: {},
          name: "FOCUS",
          createdAt: 1504795450,
          instanceId: 221759,
          isActive: false,
          isPredefined: true,
          lightSettings: [
            {
              isProxy: true,
              options: {},
              name: "",
              createdAt: 0,
              instanceId: 65539,
              color: "f1e0b5",
              hue: 0,
              saturation: 0,
              colorX: 0,
              colorY: 0,
              colorTemperature: 0,
              dimmer: 100,
              onOff: true,
            },
            {
              isProxy: true,
              options: {},
              name: "",
              createdAt: 0,
              instanceId: 65541,
              color: "f1e0b5",
              hue: 0,
              saturation: 0,
              colorX: 0,
              colorY: 0,
              colorTemperature: 0,
              dimmer: 100,
              onOff: true,
            },
            {
              isProxy: true,
              options: {},
              name: "",
              createdAt: 0,
              instanceId: 65540,
              color: "f1e0b5",
              hue: 0,
              saturation: 0,
              colorX: 0,
              colorY: 0,
              colorTemperature: 0,
              dimmer: 100,
              onOff: true,
            },
          ],
          sceneIndex: 2,
          useCurrentLightSettings: false,
        },
        "225994": {
          isProxy: true,
          options: {},
          name: "Lidt lys",
          createdAt: 1510264781,
          instanceId: 225994,
          isActive: false,
          isPredefined: false,
          lightSettings: [
            {
              isProxy: true,
              options: {},
              name: "",
              createdAt: 0,
              instanceId: 65539,
              color: "f1e0b5",
              hue: 0,
              saturation: 0,
              colorX: 0,
              colorY: 0,
              colorTemperature: 0,
              dimmer: 2,
              onOff: false,
            },
            {
              isProxy: true,
              options: {},
              name: "",
              createdAt: 0,
              instanceId: 65541,
              color: "f1e0b5",
              hue: 0,
              saturation: 0,
              colorX: 0,
              colorY: 0,
              colorTemperature: 0,
              dimmer: 2,
              onOff: false,
            },
            {
              isProxy: true,
              options: {},
              name: "",
              createdAt: 0,
              instanceId: 65540,
              color: "f1e0b5",
              hue: 0,
              saturation: 0,
              colorX: 0,
              colorY: 0,
              colorTemperature: 0,
              dimmer: 0.8,
              onOff: true,
            },
          ],
          sceneIndex: 3,
          useCurrentLightSettings: false,
        },
        "225995": {
          isProxy: true,
          options: {},
          name: "mellem lys",
          createdAt: 1520712390,
          instanceId: 225995,
          isActive: false,
          isPredefined: false,
          lightSettings: [
            {
              isProxy: true,
              options: {},
              name: "",
              createdAt: 0,
              instanceId: 65539,
              color: "f1e0b5",
              hue: 0,
              saturation: 0,
              colorX: 0,
              colorY: 0,
              colorTemperature: 0,
              dimmer: 0.8,
              onOff: true,
            },
            {
              isProxy: true,
              options: {},
              name: "",
              createdAt: 0,
              instanceId: 65541,
              color: "f1e0b5",
              hue: 0,
              saturation: 0,
              colorX: 0,
              colorY: 0,
              colorTemperature: 0,
              dimmer: 7.9,
              onOff: false,
            },
            {
              isProxy: true,
              options: {},
              name: "",
              createdAt: 0,
              instanceId: 65540,
              color: "f1e0b5",
              hue: 0,
              saturation: 0,
              colorX: 0,
              colorY: 0,
              colorTemperature: 0,
              dimmer: 0.8,
              onOff: true,
            },
          ],
          sceneIndex: 4,
          useCurrentLightSettings: false,
        },
        "225996": {
          isProxy: true,
          options: {},
          name: "Alle 1pct",
          createdAt: 1520712436,
          instanceId: 225996,
          isActive: false,
          isPredefined: false,
          lightSettings: [
            {
              isProxy: true,
              options: {},
              name: "",
              createdAt: 0,
              instanceId: 65539,
              color: "f1e0b5",
              hue: 0,
              saturation: 0,
              colorX: 0,
              colorY: 0,
              colorTemperature: 0,
              dimmer: 0.8,
              onOff: true,
            },
            {
              isProxy: true,
              options: {},
              name: "",
              createdAt: 0,
              instanceId: 65541,
              color: "f1e0b5",
              hue: 0,
              saturation: 0,
              colorX: 0,
              colorY: 0,
              colorTemperature: 0,
              dimmer: 0.8,
              onOff: true,
            },
            {
              isProxy: true,
              options: {},
              name: "",
              createdAt: 0,
              instanceId: 65540,
              color: "f1e0b5",
              hue: 0,
              saturation: 0,
              colorX: 0,
              colorY: 0,
              colorTemperature: 0,
              dimmer: 0.8,
              onOff: true,
            },
          ],
          sceneIndex: 5,
          useCurrentLightSettings: false,
        },
        "225997": {
          isProxy: true,
          options: {},
          name: "sluk alt",
          createdAt: 1520712514,
          instanceId: 225997,
          isActive: false,
          isPredefined: false,
          lightSettings: [
            {
              isProxy: true,
              options: {},
              name: "",
              createdAt: 0,
              instanceId: 65539,
              color: "f1e0b5",
              hue: 0,
              saturation: 0,
              colorX: 0,
              colorY: 0,
              colorTemperature: 0,
              dimmer: 2,
              onOff: false,
            },
            {
              isProxy: true,
              options: {},
              name: "",
              createdAt: 0,
              instanceId: 65541,
              color: "f1e0b5",
              hue: 0,
              saturation: 0,
              colorX: 0,
              colorY: 0,
              colorTemperature: 0,
              dimmer: 2,
              onOff: false,
            },
            {
              isProxy: true,
              options: {},
              name: "",
              createdAt: 0,
              instanceId: 65540,
              color: "f1e0b5",
              hue: 0,
              saturation: 0,
              colorX: 0,
              colorY: 0,
              colorTemperature: 0,
              dimmer: 0.8,
              onOff: false,
            },
          ],
          sceneIndex: 6,
          useCurrentLightSettings: false,
        },
      },
    },
  ],
  [
    "184825",
    {
      group: {
        isProxy: true,
        options: {},
        name: "Group 4",
        createdAt: 1503242162,
        instanceId: 184825,
        onOff: false,
        dimmer: 0,
        deviceIDs: [65536, 65538],
        sceneId: 204011,
        groupType: 0,
      },
      scenes: {
        "201802": {
          isProxy: true,
          options: {},
          name: "RELAX",
          createdAt: 1503242162,
          instanceId: 201802,
          isActive: false,
          isPredefined: true,
          lightSettings: [
            {
              isProxy: true,
              options: {},
              name: "",
              createdAt: 0,
              instanceId: 65538,
              color: "f1e0b5",
              hue: 0,
              saturation: 0,
              colorX: 0,
              colorY: 0,
              colorTemperature: 0,
              dimmer: 9.8,
              onOff: true,
            },
          ],
          sceneIndex: 1,
          useCurrentLightSettings: false,
        },
        "203844": {
          isProxy: true,
          options: {},
          name: "FOCUS",
          createdAt: 1503242162,
          instanceId: 203844,
          isActive: false,
          isPredefined: true,
          lightSettings: [
            {
              isProxy: true,
              options: {},
              name: "",
              createdAt: 0,
              instanceId: 65538,
              color: "f1e0b5",
              hue: 0,
              saturation: 0,
              colorX: 0,
              colorY: 0,
              colorTemperature: 0,
              dimmer: 100,
              onOff: true,
            },
          ],
          sceneIndex: 2,
          useCurrentLightSettings: false,
        },
        "204011": {
          isProxy: true,
          options: {},
          name: "EVERYDAY",
          createdAt: 1503242162,
          instanceId: 204011,
          isActive: false,
          isPredefined: true,
          lightSettings: [
            {
              isProxy: true,
              options: {},
              name: "",
              createdAt: 0,
              instanceId: 65538,
              color: "f1e0b5",
              hue: 0,
              saturation: 0,
              colorX: 0,
              colorY: 0,
              colorTemperature: 0,
              dimmer: 79.9,
              onOff: true,
            },
          ],
          sceneIndex: 0,
          useCurrentLightSettings: false,
        },
      },
    },
  ],
];

export default dummyGroups;
