const dummyDevices = [
  [
    "65536",
    {
      isProxy: true,
      options: {},
      name: "Group 4.Remote",
      createdAt: 1503242154,
      instanceId: 65536,
      type: 0,
      alive: true,
      lastSeen: 1538666004,
      otaUpdateState: 1,
      deviceInfo: {
        isProxy: true,
        options: {},
        firmwareVersion: "1.2.214",
        manufacturer: "IKEA of Sweden",
        modelNumber: "TRADFRI remote control",
        power: 3,
        serialNumber: "",
        battery: 11,
      },
      switchList: [
        {
          isProxy: true,
          options: {},
          name: "",
          createdAt: 0,
          instanceId: 0,
        },
      ],
    },
  ],
  [
    "65537",
    {
      isProxy: true,
      options: {},
      name: "Bulb.E27WS",
      createdAt: 1503241192,
      instanceId: 65537,
      type: 2,
      alive: true,
      lastSeen: 1564945153,
      otaUpdateState: 0,
      deviceInfo: {
        isProxy: true,
        options: {},
        firmwareVersion: "1.2.217",
        manufacturer: "IKEA of Sweden",
        modelNumber: "TRADFRI bulb E27 WS opal 980lm",
        power: 1,
        serialNumber: "",
      },
      lightList: [
        {
          onOff: false,
          dimmer: 9.8,
          color: "f1e0b5",
          transitionTime: 0.5,
        },
      ],
    },
  ],
  [
    "65538",
    {
      isProxy: true,
      options: {},
      name: "Group 4.Bulb.E27WS",
      createdAt: 1503241942,
      instanceId: 65538,
      type: 2,
      alive: false,
      lastSeen: 1564982124,
      otaUpdateState: 0,
      deviceInfo: {
        isProxy: true,
        options: {},
        firmwareVersion: "1.2.217",
        manufacturer: "IKEA of Sweden",
        modelNumber: "TRADFRI bulb E27 WS opal 980lm",
        power: 1,
        serialNumber: "",
      },
      lightList: [
        {
          onOff: false,
          dimmer: 0.8,
          color: "f1e0b5",
          colorTemperature: 100,
          transitionTime: 0.5,
        },
      ],
    },
  ],
  [
    "65539",
    {
      isProxy: true,
      options: {},
      name: "Group 3.Bulb.E27",
      createdAt: 1504794416,
      instanceId: 65539,
      type: 2,
      alive: true,
      lastSeen: 1565008770,
      otaUpdateState: 0,
      deviceInfo: {
        isProxy: true,
        options: {},
        firmwareVersion: "1.2.214",
        manufacturer: "IKEA of Sweden",
        modelNumber: "TRADFRI bulb E27 opal 1000lm",
        power: 1,
        serialNumber: "",
      },
      lightList: [
        {
          onOff: false,
          dimmer: 2,
          color: "f1e0b5",
          transitionTime: 0.5,
        },
      ],
    },
  ],
  [
    "65540",
    {
      isProxy: true,
      options: {},
      name: "Group 3.Bulb.E27",
      createdAt: 1504794519,
      instanceId: 65540,
      type: 2,
      alive: true,
      lastSeen: 1565008764,
      otaUpdateState: 0,
      deviceInfo: {
        isProxy: true,
        options: {},
        firmwareVersion: "1.2.214",
        manufacturer: "IKEA of Sweden",
        modelNumber: "TRADFRI bulb E27 W opal 1000lm",
        power: 1,
        serialNumber: "",
      },
      lightList: [
        {
          onOff: false,
          dimmer: 0.8,
          color: "f1e0b5",
          transitionTime: 0.5,
        },
      ],
    },
  ],
  [
    "65541",
    {
      isProxy: true,
      options: {},
      name: "Group 3.Bulb.E27",
      createdAt: 1504794598,
      instanceId: 65541,
      type: 2,
      alive: true,
      lastSeen: 1565008777,
      otaUpdateState: 0,
      deviceInfo: {
        isProxy: true,
        options: {},
        firmwareVersion: "1.2.214",
        manufacturer: "IKEA of Sweden",
        modelNumber: "TRADFRI bulb E27 opal 1000lm",
        power: 1,
        serialNumber: "",
      },
      lightList: [
        {
          onOff: false,
          dimmer: 2,
          color: "f1e0b5",
          transitionTime: 0.5,
        },
      ],
    },
  ],
  [
    "65542",
    {
      isProxy: true,
      options: {},
      name: "Remote Control Group 2",
      createdAt: 1504795178,
      instanceId: 65542,
      type: 0,
      alive: true,
      lastSeen: 1527390159,
      otaUpdateState: 0,
      deviceInfo: {
        isProxy: true,
        options: {},
        firmwareVersion: "1.2.248",
        manufacturer: "IKEA of Sweden",
        modelNumber: "TRADFRI wireless dimmer",
        power: 3,
        serialNumber: "",
        battery: 47,
      },
      switchList: [
        {
          isProxy: true,
          options: {},
          name: "",
          createdAt: 0,
          instanceId: 0,
        },
      ],
    },
  ],
  [
    "65543",
    {
      isProxy: true,
      options: {},
      name: "Group 2 dimmer",
      createdAt: 1504795441,
      instanceId: 65543,
      type: 0,
      alive: true,
      lastSeen: 1534434305,
      otaUpdateState: 0,
      deviceInfo: {
        isProxy: true,
        options: {},
        firmwareVersion: "1.2.248",
        manufacturer: "IKEA of Sweden",
        modelNumber: "TRADFRI wireless dimmer",
        power: 3,
        serialNumber: "",
        battery: 100,
      },
      switchList: [
        {
          isProxy: true,
          options: {},
          name: "",
          createdAt: 0,
          instanceId: 0,
        },
      ],
    },
  ],
  [
    "65545",
    {
      isProxy: true,
      options: {},
      name: "",
      createdAt: 1511614738,
      instanceId: 65545,
      type: 0,
      alive: true,
      lastSeen: 1542300305,
      otaUpdateState: 0,
      deviceInfo: {
        isProxy: true,
        options: {},
        firmwareVersion: "",
        manufacturer: "",
        modelNumber: "",
        power: 0,
        serialNumber: "",
      },
      switchList: [
        {
          isProxy: true,
          options: {},
          name: "",
          createdAt: 0,
          instanceId: 0,
        },
      ],
    },
  ],
];

export default dummyDevices;
// DummyDevices: dummyDevices,
// DummyGroups: dummyGroups,
// };
